import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased max-w-4xl mx-auto px-4 py-4`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
